Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 50
PerceivedComplexity:
  Max: 20
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 15
